### PR TITLE
Drop the country part of the langauge

### LINKED ISSUE #34: Drop the country part of the locale specification?
Given that the Readme itself says "At the moment cultures are not fully supported, so you can't have src/fr-CA ( sorry! ), and there are no plans for this.", and the domains themselves are set up like http://de.pinout.xyz/ and http://fr.pinout.xyz/ ; would it make things 'simpler' if e.g. https://github.com/Gadgetoid/Pinout2/tree/master/src/de-DE was renamed to just `de` and https://github.com/Gadgetoid/Pinout2/tree/master/src/fr-FR was renamed to just `fr` ?

See also: https://en.wikipedia.org/wiki/ISO_639-1 and https://en.wikipedia.org/wiki/IETF_language_tag and all that good fun... ;-)

### PR DESCRIPTION
**Pull request by lurch**
Fixes #34

### CODE REVIEW

**Comment by lurch** [comment]
This is the same as the closed #43, but I've now moved it onto it's own branch, so that it can be re-based when necessary... (@RogueM says he has some other translations he wants to commit, before this PR gets merged in)

**Comment by lurch** [comment]
Please merge #45 before merging this PR, which will allow me to simplify the code used here :-)

**Comment by Gadgetoid** [comment]
Manually merged in: https://github.com/Gadgetoid/Pinout2/commit/864b0fb96af34a05269e6a97d22fec3c29a4e498

**Comment by lurch** [comment]
Oh, how come it was manually merged in?

I hope @RogueM doesn't get too upset that this was merged in before he was ready for it? :-/

**Comment by Gadgetoid** [comment]
Whooops. I may have been a little hasty! I tend to get excited. It's not just merged, it's published!

**Comment by lurch** [comment]
Ah well, at least the "painful big merge" is done and out of the way now ;-)
(and will hopefully make things a bit simpler going forward).

**Pull request closed without merging**
