### PR TITLE
Added new boards

### PR DESCRIPTION
**Pull request by abelectronicsuk**
Hi

I have added the new boards from AB Electronics UK and updated the descriptions for several of our existing boards.

### CODE REVIEW

**Comment by RogueM** [comment]
cheers, all looks good! we've just pushed a big update but I'll try to get @Gadgetoid to push this lot as it seems ready out of the box!

**Comment by RogueM** [comment]
actually you have an error in ab-servo-pwm-pi-zero.md, did you mean BCM4 for the GPIO? (physical 4 is a 5V pin, which our renderer will flag)

**Comment by RogueM** [comment]
found the answer on your product page, amended! the schematics does not show phys pin 25 as grounded, which is correct?

**Comment by Gadgetoid** [comment]
You guys are fantastic <3 I'll push an update out ASAP.

**Pull request merged**
